quarkus:
  jackson:
    serialization-inclusion: non-empty
  rest:
    jackson:
      optimization:
        # See https://quarkus.io/blog/quarkus-metaprogramming/
        enable-reflection-free-serializers: true

"%prod":
  quarkus:
    datasource:
      username: fruits
      password: fruits
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
        max-size: 20
    hibernate-orm:
      sql-load-script: ""

