spring:
  datasource:
    username: fruits
    password: fruits
    url: jdbc:postgresql://localhost:5432/fruits
    hikari:
      maximum-pool-size: 20
      auto-commit: false
  jackson:
    default-property-inclusion: non_empty
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
        default_batch_fetch_size: 16
        connection:
          provider_disables_autocommit: true

