server:
  host: 0.0.0.0
  port: 8080
  readTimeoutSeconds: 20
  writeTimeoutSeconds: 35
  idleTimeoutSeconds: 15

database:
  host: localhost
  port: 5432
  name: fruits
  user: fruits
  password: fruits
  sslmode: disable
  maxConns: 20
  minConns: 4
  maxConnIdleTimeSeconds: 300
  maxConnLifetimeSeconds: 1800
