micronaut:
  application:
    name: micronaut5
  executors:
    virtual:
      type: fixed
      nThreads: 20
      virtual: false

jackson:
  serializationInclusion: NON_EMPTY

datasources:
  default:
    username: fruits
    password: fruits
    url: jdbc:postgresql://localhost:5432/fruits
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 20
    auto-commit: false

jpa:
  default:
    entity-scan:
      packages:
        - org.acme.domain
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: jcache
        default_batch_fetch_size: 16
        connection:
          provider_disables_autocommit: true
